WIP: feat(entity-table-widget): add sticky, hide settings options, selections
xm-online/xm-webapp pull request #1266
Opened 2021-11-08 14:26 UTC by oscaryald

2022-02-09 14:34 UTC, Sumragen approved these changes

2022-02-09 14:35 UTC, grankovsky submitted a review, later dismissed

2022-02-09 14:54 UTC, OlenaSVT submitted a review, later dismissed

2022-03-11 13:11 UTC, Kaskyi requested changes

2022-03-11 13:11 UTC, Kaskyi commented on packages/components/table/column/table-column-dynamic-cell.ts
> +import { ShowHideColumnsSettingsModule } from '@xm-ngx/ext/entity-webapp-ext/module/table/show-hide-columns-setting-widget';
dont use private packages

2023-03-01 07:54 UTC, closed without merging