feat(multilingual-control): create new dynamic multilingual widget
xm-online/xm-webapp pull request #1324
Opened 2022-02-18 15:04 UTC by EKrasovskiy

…instead old

2022-02-21 08:11 UTC, grankovsky submitted a review, later dismissed

2022-02-21 09:16 UTC, Kaskyi approved these changes

2022-02-21 09:16 UTC, Kaskyi commented on packages/components/xm-multilingual-control/index.ts
> +export { XmMultilingualModule } from '@xm-ngx/components/xm-multilingual-control/xm-multilingual.module';
`./` instead of `@xm-ngx/components/`

2022-02-21 10:24 UTC, Kaskyi submitted a review, later dismissed

2022-02-21 10:31 UTC, EKrasovskiy commented on packages/components/xm-multilingual-control/index.ts
> +export { XmMultilingualModule } from '@xm-ngx/components/xm-multilingual-control/xm-multilingual.module';
fixed

2022-02-22 14:45 UTC, Sumragen requested changes

2022-02-22 14:45 UTC, Sumragen commented on packages/components/xm-multilingual-control/xm-multilingual-control.component.ts
> +        this._options = baseOptions;
Could be simplified by defining mapper variable with enum as a key.

2022-02-22 14:45 UTC, Sumragen commented on packages/components/xm-multilingual-control/xm-multilingual-control.component.ts
> +    public _onTouched: (v?: unknown) => void = () => undefined;
Syntax with underscore always means that class propery should be private.

2022-02-22 14:45 UTC, Sumragen commented on packages/components/xm-multilingual-control/xm-multilingual-control.component.ts
> +            .pipe(take(1))
Probably we could use static property to achieve that behavior

2022-02-22 14:45 UTC, Sumragen commented on packages/components/xm-multilingual-control/xm-multilingual-control.component.ts
> +            .pipe(take(1))
Also we could use component config in order to determine necessary languages.

2022-03-11 13:20 UTC, Kaskyi requested changes

2022-03-11 13:20 UTC, Kaskyi commented on packages/components/xm-multilingual-control/xm-multilingual-control.component.ts
> +    public setDisabledState?(isDisabled: boolean): void {
question mark at the end ? the method returns `void`

2022-03-11 13:20 UTC, Kaskyi commented on packages/components/xm-multilingual-control/xm-multilingual-control.component.ts
> +        mat-label {
The global styles may create an unpredictable behaviour. Make sure to wrap them with a base class like `.xm-multilingual-control`

2022-04-29 19:28 UTC, EKrasovskiy commented
https://github.com/xm-online/xm-webapp/pull/1334

2022-04-29 19:28 UTC, closed without merging