feat(multi-language-widget): add multi lang widget to dynamic registry
xm-online/xm-webapp pull request #1334
Opened 2022-03-30 14:39 UTC by zverbeta

2022-03-30 14:49 UTC, Kaskyi approved these changes

2022-03-31 05:55 UTC, Kaskyi requested changes

2022-03-31 05:55 UTC, Kaskyi commented on packages/components/multilanguage/xm-multi-language.component.ts
> +export type MultiLanguageListModel = MultiLanguageDataModel;
tsdoc https://tsdoc.org/ style : "/** */"

2022-03-31 07:14 UTC, Kaskyi approved these changes

2022-03-31 07:32 UTC, grankovsky approved these changes

2022-03-31 07:40 UTC, merged