feat(presentation-options-and-config): render dynamic widget with nam…
xm-online/xm-webapp pull request #1357
Opened 2022-05-12 07:14 UTC by zverbeta

…e input `config`

2022-05-12 07:52 UTC, Sumragen requested changes
Shall `PresentationBase` be used as parent class for widgets?

2022-05-12 08:08 UTC, zverbeta commented
PresentationBase used to not only for widgets, but controls to. Dynamic widgets can accept both `config` and `options`

2022-05-12 08:35 UTC, Kaskyi requested changes

2022-05-12 08:35 UTC, Kaskyi commented on packages/dynamic/src/presentation/xm-dynamic-presentation-base.directive.ts
> +    config?: O;
Do u want to render widgets inside presentation components ?

2022-05-12 11:40 UTC, zverbeta commented on packages/dynamic/src/presentation/xm-dynamic-presentation-base.directive.ts
> +    config?: O;
Yes, because presentation directive render all types of dynamic components: widgets, components, controls

2022-05-25 11:57 UTC, Kaskyi commented on packages/dynamic/src/presentation/xm-dynamic-presentation-base.directive.ts
> +    config?: O;
presentation/controls - is a part of dynamic feature
widget/dashboard is a part of dashboard feature
dynamic-widget is combination of dashboard and dynamic features.
config it is a property of widget not a presentation. We should add one more abstract layer without configs and options.

2022-09-15 10:12 UTC, Kaskyi approved these changes

2022-09-16 07:40 UTC, major13ua approved these changes

2022-09-16 07:58 UTC, sergeysenja1992 approved these changes

2022-09-16 11:48 UTC, Sumragen approved these changes

2022-09-16 11:48 UTC, Sumragen commented
Will discuss later which field shall we left

2022-09-20 07:53 UTC, merged