feat(web-app): add link to doc
xm-online/xm-webapp pull request #1371
Opened 2022-05-27 13:56 UTC by grankovsky

2022-05-27 15:40 UTC, Kaskyi requested changes

2022-05-27 15:40 UTC, Kaskyi commented on packages/administration/src/dashboards-config/widget-edit/widget-edit.component.html
> +          Docs <a [routerLink]="'/dashboard/ui-docs'"> <mat-icon class="example-tab-icon">open_in_new</mat-icon></a>
example tab icon - ?

2022-12-09 14:10 UTC, Bozonych approved these changes

2022-12-09 14:58 UTC, zverbeta approved these changes

2022-12-09 15:06 UTC, merged