fix(xm-text-control): mat-hint styles fixed
xm-online/xm-webapp pull request #1372
Opened 2022-05-30 14:42 UTC by LevBD

2022-05-30 14:55 UTC, Kaskyi requested changes

2022-05-30 14:55 UTC, Kaskyi commented on packages/components/text/text-control/xm-text-control.ts
> +        '.mat-hint { max-width: fit-content }',
ViewEncapsulation.None - all styles become global

2022-05-31 08:09 UTC, LevBD commented on packages/components/text/text-control/xm-text-control.ts
> +        '.mat-hint { max-width: fit-content }',
Changed styles to inline styles

2022-05-31 09:23 UTC, Kaskyi submitted a review, later dismissed

2022-06-01 06:37 UTC, Sumragen submitted a review, later dismissed

2022-06-06 08:18 UTC, Sumragen submitted a review, later dismissed

2022-06-06 09:53 UTC, Kaskyi approved these changes

2022-06-08 13:15 UTC, merged