WIP: Feat/update angular
xm-online/xm-webapp pull request #1378
Opened 2022-06-03 07:13 UTC by Sumragen

2022-06-03 10:34 UTC, Kaskyi requested changes

2022-06-03 10:34 UTC, Kaskyi commented on proxy.conf.js
> +        target: 'http://172.20.75.176/',
remove

2022-06-03 10:34 UTC, Kaskyi commented on packages/shared/operators/src/download.ts
> +    // @ts-ignore
use types

2022-06-03 10:34 UTC, Kaskyi commented on packages/cli/src/ext-themes-command.ts
> +                // includePaths: ['src', 'src/styles', this.config.extDir],
remove

2022-06-03 10:34 UTC, Kaskyi commented on packages/components/sidebar-right/xm-sidebar-right.module.ts
> +            ngModuleRef: cfr['ngModule']
refactor

2022-06-07 14:37 UTC, Kaskyi commented on packages/components/sidebar-right/xm-sidebar-right.module.ts
> +            ngModuleRef: cfr['ngModule']
and squash

2022-08-02 11:48 UTC, major13ua commented on package.json
> +    "get-version": "printf $npm_package_version"
Please update major version of application

2022-08-02 11:49 UTC, sergeysenja1992 commented on package.json
> +  "version": "3.6.99",
update major version

2022-08-02 11:54 UTC, Kaskyi requested changes

2022-08-02 11:54 UTC, Kaskyi commented on packages/cli/src/ext-themes-command.ts
> -import { packageImporter } from './ext-theming/node-sass-package-importer';
looks like we no need `packageImporter`.
Please , remove all files from `packages/cli/src/ext-theming`

2022-08-02 11:54 UTC, Kaskyi commented on packages/components/sidebar-right/xm-sidebar-right.module.ts
> +            ngModuleRef: cfr['ngModule']
there must be a public variable somewhere.

2022-08-22 12:16 UTC, sergeysenja1992 approved these changes

2022-10-23 13:42 UTC, closed without merging