Feat/update angular 14
xm-online/xm-webapp pull request #1437
Opened 2022-09-01 14:44 UTC by Sumragen

2022-09-05 10:45 UTC, grankovsky approved these changes

2022-09-05 12:18 UTC, sergeysenja1992 submitted a review, later dismissed

2022-09-05 12:36 UTC, Kaskyi requested changes

2022-09-05 12:36 UTC, Kaskyi commented on CHANGELOG.md
> +
add description like 
```
# 3.2.3 (2021-05-27)

### Features
```

2022-09-05 12:36 UTC, Kaskyi commented on tsconfig.json
> +      "rxjs": ["node_modules/rxjs"],
not sure if this is necessary

2022-09-05 12:36 UTC, Kaskyi commented on src/styles.scss
> -@import './styles/theme';
vodafone

2022-09-05 12:49 UTC, Kaskyi commented on src/app/modules/xm-shared/xm-shared.module.ts
> +        // XmAlertModule,
remove?

2022-09-05 12:50 UTC, Kaskyi commented on proxy.conf.js
> +        // target: "http://xm.test.xm-online.com.ua",
vf

2022-09-05 12:53 UTC, Kaskyi commented on packages/components/sidebar-right/xm-sidebar-right.module.ts
> +            ngModuleRef: cfr['ngModule']
should be an variable

2022-09-05 12:56 UTC, Kaskyi commented on packages/alert/src/xm-alert.service.ts
> +            // TODO: Check settings.title type
remove?

2022-09-05 12:56 UTC, Kaskyi commented on packages/alert/src/toaster/alert-error.component.ts
> +            // TODO: handle type incompatibility
remove?

2022-09-05 14:09 UTC, oscaryald submitted a review, later dismissed

2022-09-05 15:22 UTC, Sumragen commented on tsconfig.json
> +      "rxjs": ["node_modules/rxjs"],
otherwise we will retrieve ts errors due to incompatible versions of nested dependencies

2022-09-05 15:23 UTC, Sumragen commented on CHANGELOG.md
> +
Nice point. I'll fill detailed info about changes

2022-09-05 15:25 UTC, Sumragen commented on src/styles.scss
> -@import './styles/theme';
reverted that miss

2022-09-06 08:41 UTC, EKrasovskiy commented on src/styles/_theme.scss
> +// Theme Styles
shoul be reverted

2022-09-07 18:34 UTC, Sumragen commented on packages/styles/src/vendor/_chartist.scss
> +//@import "~chartist/dist/index.css";
Not removed, but moved above

2022-09-07 19:40 UTC, Sumragen commented on src/styles/_theme.scss
> +// Theme Styles
agree

2022-09-07 19:41 UTC, Sumragen commented on packages/alert/src/xm-alert.service.ts
> +            // TODO: Check settings.title type
isn't removed. it's below

2022-10-07 15:04 UTC, Kaskyi commented
fixes https://github.com/xm-online/xm-webapp/issues/1183#issue-961704145

2022-10-15 15:43 UTC, Sumragen commented on packages/components/sidebar-right/xm-sidebar-right.module.ts
> +            ngModuleRef: cfr['ngModule']
This `hack` will be changed in next PR dedicated to dynamic loaders refactoring

2022-10-16 05:52 UTC, Sumragen commented on src/app/modules/xm-shared/xm-shared.module.ts
> +        // XmAlertModule,
it's a duplicate of 26's line

2022-10-16 06:55 UTC, Kaskyi approved these changes

2022-10-16 07:00 UTC, Olensavchenko approved these changes

2022-10-16 07:40 UTC, LevBD approved these changes

2022-10-16 08:09 UTC, merged