dynamic loader refactoring
xm-online/xm-webapp pull request #1511
Opened 2023-01-04 15:56 UTC by Sumragen

2023-01-04 17:53 UTC, Kaskyi approved these changes

2023-01-06 09:42 UTC, sergeysenja1992 approved these changes

2023-02-01 16:11 UTC, Kaskyi requested changes
Require module resolving fixes
Done!

2023-02-09 15:47 UTC, Olensavchenko approved these changes

2023-02-09 18:18 UTC, merged