feat(confirm-dialog): fix confirm dialog empty controls
xm-online/xm-webapp pull request #1639
Opened 2023-04-14 11:52 UTC by zverbeta

2023-04-14 12:20 UTC, Bozonych approved these changes

2023-04-14 12:39 UTC, Kaskyi approved these changes

2023-04-17 22:32 UTC, Kaskyi requested changes

2023-04-17 22:32 UTC, Kaskyi commented on packages/dynamic/control/xm-dynamic-control.directive.ts
> +        from(this.createComponent()).pipe(
why do you pipe from promise and switchMap it ? You can just this.controlValue.asObservable().pipe(

2023-04-18 06:17 UTC, zverbeta commented on packages/dynamic/control/xm-dynamic-control.directive.ts
> +        from(this.createComponent()).pipe(
Because we needs a control instance

2023-04-18 12:41 UTC, Kaskyi commented on packages/dynamic/control/xm-dynamic-control.directive.ts
> +        from(this.createComponent()).pipe(
when user change selector / component recreates https://github.com/xm-online/xm-webapp/pull/1639/files#diff-6ddc14443726705185dd92c39c15da1745c9585ae0f51d3dd06044dcb9e2ae22R117

2023-04-19 13:11 UTC, Kaskyi approved these changes

2023-04-20 10:27 UTC, grankovsky approved these changes

2023-04-20 11:07 UTC, merged