feat(autocomplete-control): add messageErrors, startFromCharSearch pa…
xm-online/xm-webapp pull request #1658
Opened 2023-05-04 10:18 UTC by oscaryald

…rams

2023-05-04 11:59 UTC, zverbeta requested changes

2023-05-04 11:59 UTC, zverbeta commented on packages/components/autocomplete-control/autocomplete-control.ts
> +    constructor(
This contrustructor should be moved to XmAutocompleteControl or extends from NgControlAccessor

2023-05-04 12:27 UTC, Kaskyi approved these changes

2023-05-05 07:33 UTC, grankovsky approved these changes

2023-05-05 09:46 UTC, zverbeta approved these changes

2023-05-05 11:39 UTC, merged