Feature/packages interfaces
xm-online/xm-webapp pull request #1669
Opened 2023-05-16 23:18 UTC by Kaskyi

2023-05-18 16:47 UTC, grankovsky approved these changes

2023-05-18 17:44 UTC, zverbeta approved these changes

2023-05-24 17:24 UTC, sergeysenja1992 approved these changes

2023-05-24 17:29 UTC, Sumragen requested changes
Everything is fine. Wait for QA testing results

2023-05-30 19:49 UTC, grankovsky approved these changes

2023-07-21 16:29 UTC, Kaskyi commented
merged refactor/package-components

2023-07-25 15:11 UTC, merged