Feature/schema validation js
xm-online/xm-webapp pull request #1713
Opened 2023-06-29 02:23 UTC by Kaskyi

2023-06-29 05:54 UTC, Sumragen requested changes

2023-06-29 05:54 UTC, Sumragen commented on packages/dashboards/validate.js
> +                logger.warn(`Object is invalid name=${widget.name}!`);
Add also dashboard key to message. It will help us find widget config with common name, such as `toolbar`

2023-06-29 18:09 UTC, Kaskyi commented on packages/dashboards/validate.js
> +                logger.warn(`Object is invalid name=${widget.name}!`);
done

2023-06-29 18:09 UTC, Kaskyi commented on packages/dashboards/validate.js
> +                logger.warn(`Object is invalid name=${widget.name}!`);
done

2023-06-29 18:36 UTC, Sumragen approved these changes

2023-06-30 11:46 UTC, zverbeta approved these changes

2023-06-30 12:12 UTC, grankovsky approved these changes

2023-06-30 12:16 UTC, merged