refactor(package): remove dublicates build, serve
xm-online/xm-webapp pull request #1714
Opened 2023-06-29 18:55 UTC by Kaskyi

2023-06-30 06:21 UTC, sergeysenja1992 requested changes
we need clarify number of commands that we using BEFORE remove it

2023-06-30 06:22 UTC, sergeysenja1992 commented on package.json
> -    "dev:aot": "npm run prebuild && ng serve --proxy-config local.proxy.conf.js --live-reload  --host=0.0.0.0 --configuration production --aot=true",
how to start local with aot?

2023-06-30 06:52 UTC, Sumragen commented on package.json
> -    "dev:aot": "npm run prebuild && ng serve --proxy-config local.proxy.conf.js --live-reload  --host=0.0.0.0 --configuration production --aot=true",
AOT is the default compiler starting in Angular 9.
Moreover, according to `angular.json` config file `serve-production` configuration includes `aot: true`.

2023-06-30 06:53 UTC, Sumragen approved these changes

2023-07-03 14:15 UTC, sergeysenja1992 commented on package.json
> +    "build:prod": "npm run prebuild && ng build --configuration production --statsJson",
@Kaskyi  we need build-aot alias

2023-07-03 14:17 UTC, sergeysenja1992 commented on package.json
> +    "start": "npm run prebuild && ng serve --proxy-config local.proxy.conf.js --live-reload --host=0.0.0.0",
add start without theme generation

2023-07-03 20:15 UTC, Kaskyi commented on package.json
> +    "start": "npm run prebuild && ng serve --proxy-config local.proxy.conf.js --live-reload --host=0.0.0.0",
add start:minimal

2023-07-03 20:17 UTC, Kaskyi commented on package.json
> +    "build:prod": "npm run prebuild && ng build --configuration production --statsJson",
done

2023-07-04 09:25 UTC, zverbeta approved these changes

2023-07-04 09:32 UTC, sergeysenja1992 approved these changes

2023-07-04 09:35 UTC, merged