refactor(common-entity-webapp-ext): move to packages
xm-online/xm-webapp pull request #1876
Opened 2023-10-26 05:44 UTC by Kaskyi

2023-10-26 07:27 UTC, sergeysenja1992 commented on packages/common-entity-webapp-ext/entity-widget/entity-widget.component.ts
> +        // if (DEBUG_INFO_ENABLED) {
?

2023-10-26 14:32 UTC, Kaskyi commented on packages/common-entity-webapp-ext/entity-widget/entity-widget.component.ts
> +        // if (DEBUG_INFO_ENABLED) {
done

2023-10-27 09:08 UTC, sergeysenja1992 requested changes

2023-10-27 09:08 UTC, sergeysenja1992 commented on packages/common-entity-webapp-ext/entity-widget/entity-widget.component.ts
> +        this.logger.debug(`entity=${JSON.stringify(this.xmEntity)}`);
this.logger.debug write wrong line of code in console

2023-10-27 09:09 UTC, sergeysenja1992 commented on packages/common-entity-webapp-ext/entity-widget/entity-widget.component.ts
> +                            ? this.xmEntitySpec.links.map((spec) => this.addInterfaceSpec(spec, this.entityUiConfig))
before formatting better

2023-10-30 08:00 UTC, grankovsky approved these changes

2023-10-30 10:10 UTC, denisogolubev approved these changes

2023-10-30 10:10 UTC, denisogolubev commented on packages/common-entity-webapp-ext/entity-fab-actions/entity-fab-actions.component.ts
> +enum XM_EVENT_LIST {
It's better to name an enum using the UpperCase naming convention, following the TS official documentation:
https://www.typescriptlang.org/docs/handbook/enums.html

2023-11-10 17:39 UTC, Kaskyi commented on packages/common-entity-webapp-ext/entity-widget/entity-widget.component.ts
> +        this.logger.debug(`entity=${JSON.stringify(this.xmEntity)}`);
done

2023-11-10 17:39 UTC, Kaskyi commented on packages/common-entity-webapp-ext/entity-fab-actions/entity-fab-actions.component.ts
> +enum XM_EVENT_LIST {
done

2023-11-10 17:39 UTC, Kaskyi commented on packages/common-entity-webapp-ext/entity-widget/entity-widget.component.ts
> +                            ? this.xmEntitySpec.links.map((spec) => this.addInterfaceSpec(spec, this.entityUiConfig))
done

2023-11-10 19:58 UTC, closed without merging