refactor(dashboard/home): move to packages
xm-online/xm-webapp pull request #1883
Opened 2023-10-26 17:55 UTC by Kaskyi

2023-10-27 09:07 UTC, sergeysenja1992 requested changes
Why we need move home to packages?

2023-10-27 14:19 UTC, sergeysenja1992 approved these changes

2023-10-27 20:14 UTC, Kaskyi commented
> Why do we need to move the home to packages?

To remove all code from the /src/app folder and keep only the config file. The home serves for the login page generation. It could be replaced with custom implementation.

2023-10-30 08:09 UTC, denisogolubev approved these changes

2023-11-03 15:47 UTC, grankovsky approved these changes

2023-11-10 20:43 UTC, merged