Angular 17 ivy
xm-online/xm-webapp pull request #1923
Opened 2023-12-05 16:15 UTC by zverbeta

2023-12-06 12:24 UTC, sergeysenja1992 commented on packages/dynamic/cell/xm-dynamic-cell.directive.ts
> +export const XM_DYNAMIC_TABLE_ROW = new InjectionToken<unknown>('XM_DYNAMIC_TABLE_ROW');
what reason for this change?

2023-12-06 12:27 UTC, sergeysenja1992 commented on packages/dynamic/control/xm-dynamic-control.directive.ts
> +    @Input() public declare value: V;
can we avoid declare?

2023-12-06 12:28 UTC, zverbeta commented on packages/dynamic/cell/xm-dynamic-cell.directive.ts
> +export const XM_DYNAMIC_TABLE_ROW = new InjectionToken<unknown>('XM_DYNAMIC_TABLE_ROW');
@Kaskyi Could we keep both?

2023-12-06 16:01 UTC, zverbeta commented on packages/dynamic/cell/xm-dynamic-cell.directive.ts
> +export const XM_DYNAMIC_TABLE_ROW = new InjectionToken<unknown>('XM_DYNAMIC_TABLE_ROW');
@sergeysenja1992  Github is showing wrong diff. Token XM_DYNAMIC_TABLE_CELL still exist

2023-12-08 16:21 UTC, Kaskyi approved these changes

2023-12-08 16:21 UTC, Kaskyi commented
pls sqush
<img width="526" alt="image" src="https://github.com/xm-online/xm-webapp/assets/12814213/10138963-cd91-4a12-8717-ff11085d396f">

2023-12-08 19:29 UTC, Kaskyi commented on packages/dynamic/control/xm-dynamic-control.directive.ts
> +    @Input() public declare value: V;
its is required for such cases and applies only for packages. Its workaround because of angular derived class `@Input()` bug.

2023-12-28 12:29 UTC, sergeysenja1992 commented on package.json
> +    "ngx-mat-select-search": "^7.0.5",
pls use fixed version

2023-12-28 12:30 UTC, sergeysenja1992 commented on package.json
> +    "@types/google.maps": "^3.54.10",
pls use fixed version to avoid unpredictable regression

2023-12-28 12:32 UTC, sergeysenja1992 commented on packages/components/table/collections/xm-table-array-collection-controller.ts
> +    public declare config: XmTableArrayCollectionControllerConfig;
can we avoid declare here?

2023-12-28 12:58 UTC, Kaskyi commented on packages/components/table/collections/xm-table-array-collection-controller.ts
> +    public declare config: XmTableArrayCollectionControllerConfig;
Yes, we can refactor `AXmTableLocalPageableCollectionController` and make property `config` generic, but it's extra work. We could just `declare` that the field type is overridden.

2023-12-28 14:05 UTC, sergeysenja1992 commented on packages/styles/README.md
> +@import '@angular/material';
pls add this details to migration description

2023-12-28 14:05 UTC, sergeysenja1992 commented on packages/styles/README.md
> +@import '@angular/material';
and other like this too

2023-12-28 14:19 UTC, sergeysenja1992 commented on packages/components/table/collections/xm-table-array-collection-controller.ts
> +    public declare config: XmTableArrayCollectionControllerConfig;
Why we need put declare to overridden params?
can you send link to this specification?
Should be present way to disable it in typescript config.

2023-12-28 14:20 UTC, sergeysenja1992 commented on packages/dynamic/presentation/xm-dynamic-presentation.directive.ts
> +    @Input() public declare class: string;
looks like unnecessary code clutter

2023-12-28 14:37 UTC, sergeysenja1992 commented on package.json
> +    "@angular/cdk": "17.0.1",
17.0.4?

2023-12-28 14:40 UTC, zverbeta commented on package.json
> +    "@types/google.maps": "^3.54.10",
+

2023-12-28 14:40 UTC, zverbeta commented on package.json
> +    "ngx-mat-select-search": "^7.0.5",
+

2023-12-28 14:44 UTC, zverbeta commented on package.json
> +    "@angular/cdk": "17.0.1",
+

2023-12-28 15:16 UTC, sergeysenja1992 requested changes
we need look for workaround to avoid declare keyword in existing code

2023-12-28 15:24 UTC, sergeysenja1992 commented on packages/components/table/collections/xm-table-array-collection-controller.ts
> +    public declare config: XmTableArrayCollectionControllerConfig;
Maybe any official documentation?
It's look very strange. I can't believe without strong proofs.

2023-12-28 15:43 UTC, Kaskyi commented on packages/dynamic/presentation/xm-dynamic-presentation.directive.ts
> +    @Input() public declare class: string;
`declare` works like `@ts-ignore`, angular does not check the base class declaration (as far as I know). A good solution is to remove it because it is already in the parent class. But the last time I tried, it failed at runtime.

2023-12-28 15:46 UTC, Kaskyi commented on packages/components/table/collections/xm-table-array-collection-controller.ts
> +    public declare config: XmTableArrayCollectionControllerConfig;
It is field override - there should not be such code by default. Usually, it implements with the method `@override getSomething()`.

2023-12-28 16:09 UTC, sergeysenja1992 commented on packages/components/table/collections/xm-table-array-collection-controller.ts
> +    public declare config: XmTableArrayCollectionControllerConfig;
@Kaskyi  Can you just explain for me what is `declare`. Documentation? Links? etc?
And link to documentation why we need this?

2023-12-28 17:44 UTC, Kaskyi commented on packages/components/table/collections/xm-table-array-collection-controller.ts
> +    public declare config: XmTableArrayCollectionControllerConfig;
https://www.typescriptlang.org/docs/handbook/declaration-files/by-example.html#objects-with-properties

2023-12-28 19:09 UTC, zverbeta commented on packages/components/table/collections/xm-table-array-collection-controller.ts
> +    public declare config: XmTableArrayCollectionControllerConfig;
@sergeysenja1992 https://github.com/microsoft/TypeScript/issues/45076

2023-12-28 19:10 UTC, zverbeta commented on packages/components/table/collections/xm-table-array-collection-controller.ts
> +    public declare config: XmTableArrayCollectionControllerConfig;
https://github.com/ microsoft/TypeScript/issues/45076

2023-12-28 19:11 UTC, zverbeta commented on packages/components/table/collections/xm-table-array-collection-controller.ts
> +    public declare config: XmTableArrayCollectionControllerConfig;
https://www.typescriptlang.org/tsconfig#useDefineForClassFields

2024-01-03 12:12 UTC, sergeysenja1992 approved these changes

2024-01-08 10:31 UTC, andrewkikot approved these changes

2024-01-08 10:44 UTC, Bozonych approved these changes

2024-01-08 12:27 UTC, merged