fix(xm-date-range): fix date locale on change acc settings
xm-online/xm-webapp pull request #1980
Opened 2024-02-05 14:06 UTC by oscaryald

fix date locale on change account settings

2024-02-05 15:53 UTC, Sumragen commented on packages/components/date-range/xm-date-range.component.ts
> +            });
Looks like something similar to xmPrincipal.getLang(), isn't it?

2024-02-06 08:08 UTC, oscaryald commented on packages/components/date-range/xm-date-range.component.ts
> +            });
changed it, thanks

2024-02-06 08:11 UTC, sergeysenja1992 approved these changes

2024-02-06 09:50 UTC, Bozonych approved these changes

2024-02-06 09:56 UTC, zverbeta requested changes
I see it as a separate pipe

2024-02-06 10:40 UTC, zverbeta approved these changes

2024-02-06 10:42 UTC, merged