feat(xm-table): add controllers, getControllerByKey, elastic-request-…
xm-online/xm-webapp pull request #2022
Opened 2024-03-07 13:30 UTC by oscaryald

add controllers, getControllerByKey into service, elastic-request-builder add createDefaultFiltersToRequest

2024-03-07 13:50 UTC, Sumragen requested changes

2024-03-07 13:50 UTC, Sumragen commented on packages/dynamic/src/services/xm-dynamic-injection-token-store.service.ts
> +    }
DynamicInjectionTokenStoreService responsible only for injection tokens.
It's possibly the better way to have a separate class that will extend components and services.
something like:
```
export class DynamicInstance {

    protected injector = inject(Injector);
    private injectionTokenService = inject(XmDynamicInjectionTokenStoreService);

    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
    protected getControllerByKey<T = any>(key: string, options?: InjectOptions): T {
        const providerToken: ProviderToken<any> = this.injectionTokenService.resolve(key);
        return this.injector.get(providerToken, undefined, options);
    }
}

```

2024-03-07 15:28 UTC, oscaryald commented on packages/dynamic/src/services/xm-dynamic-injection-token-store.service.ts
> +    }
created separate XmDynamicInstanceService

2024-03-08 15:14 UTC, Sumragen approved these changes

2024-03-11 10:35 UTC, Bozonych approved these changes

2024-03-11 11:00 UTC, denisogolubev approved these changes

2024-03-11 11:46 UTC, Olensavchenko approved these changes

2024-03-11 11:48 UTC, merged