fix(xm-table-filter-chips): displaying chips items
xm-online/xm-webapp pull request #2039
Opened 2024-03-20 13:47 UTC by LevBD

fix displaying chips items
![Знімок екрана 2024-03-20 о 15 46 54](https://github.com/xm-online/xm-webapp/assets/53058777/1c52b0e0-b9ec-4a0b-bd4a-9f7406a332b0)

2024-03-20 15:33 UTC, Kaskyi approved these changes

2024-03-20 16:42 UTC, zverbeta requested changes
Magic number

2024-03-25 13:26 UTC, zverbeta approved these changes

2024-03-25 13:48 UTC, denisogolubev approved these changes

2024-03-25 14:01 UTC, merged