feat: add save method to config
xm-online/xm-webapp pull request #2084
Opened 2024-04-22 14:43 UTC by Olensavchenko

2024-04-22 14:46 UTC, LevBD approved these changes

2024-04-22 17:56 UTC, Kaskyi commented on packages/components/table/collections/xm-table-array-collection-controller.ts
> +        if (this.config?.save?.controller) {
this.config already визначена. Намагайтеся не використовувати нульові значення; вони призводять до непередбачуваної поведінки. Визначте значення за замовчуванням під час ініціалізації.

Це if/else виглядає як архітектурна прогалина. бажано визначити key and key за замовчуванням і передати в getEntityController. Будь ласка, зробіть strict типизацію.

2024-04-23 08:17 UTC, Sumragen commented on packages/components/table/collections/xm-table-array-collection-controller.ts
> +        if (this.config?.save?.controller) {
ChatGPT, is it you?

2024-04-23 09:24 UTC, zverbeta requested changes

2024-04-23 09:24 UTC, zverbeta commented on packages/components/table/collections/xm-table-array-collection-controller.ts
> -import { XmToasterService } from '@xm-ngx/toaster';
Could you adjust your linter, formatter?

2024-04-23 09:24 UTC, zverbeta commented on packages/components/table/collections/xm-table-array-collection-controller.ts
> +        this.entity = await firstValueFrom(this.getEntityController()[this.config?.entityController?.method || 'entity$']());
For easier debugging and reading make it in two lines

2024-04-23 09:24 UTC, zverbeta commented on packages/components/table/collections/xm-table-array-collection-controller.ts
> +                saveResult.subscribe();
Could we unsubscribe from the inner observable or using take(1) operator?

2024-04-23 10:39 UTC, Olensavchenko commented on packages/components/table/collections/xm-table-array-collection-controller.ts
> +        if (this.config?.save?.controller) {
if/else не можна видалити або задати дефолтне значення save бо потрібна зворотня сумісність

2024-04-23 10:39 UTC, Olensavchenko commented on packages/components/table/collections/xm-table-array-collection-controller.ts
> +        if (this.config?.save?.controller) {
інше прийнято

2024-04-23 10:42 UTC, Olensavchenko commented on packages/components/table/collections/xm-table-array-collection-controller.ts
> -import { XmToasterService } from '@xm-ngx/toaster';
done

2024-04-23 10:42 UTC, Olensavchenko commented on packages/components/table/collections/xm-table-array-collection-controller.ts
> +        this.entity = await firstValueFrom(this.getEntityController()[this.config?.entityController?.method || 'entity$']());
done

2024-04-23 10:43 UTC, Olensavchenko commented on packages/components/table/collections/xm-table-array-collection-controller.ts
> +                saveResult.subscribe();
done

2024-04-23 11:34 UTC, zverbeta approved these changes

2024-04-23 12:00 UTC, Sumragen approved these changes

2024-04-23 12:04 UTC, merged

2024-04-23 17:34 UTC, Kaskyi commented on packages/components/table/collections/xm-table-array-collection-controller.ts
> +        if (this.config?.save?.controller) {
мене турбує 3 моменти
- відсутність строгоі типізаціі данних
- динамічні проперті
- конфіг 

- відсутність строгоі типізаціі 
this.getEntityController(this.config?.save?.controller?.key)[this.config?.save?.controller?.method] 
- як це не повинно працювати(риторичне питання), код не впаде на call from undefined але далі впаде бо отримає undefined
повинно бути так:
default_save_controller = ...
save_controller = get_save_controller_or_default(this.config.save, default_save_controller)
this.getEntityController(save_controller.key)[save_controller.method] 


- динамічні проперті
ох це біда, все стало ще більш запутано, хотілось би інтерфейс

- конфіг 
save?: {
        controller?:
клас може отримувавти Partial<> 
але працювати повивен задекларованими змінними
це ворерауд (він повивн бути на рівні отримання конфігу - у вас не валідний конфіг компонентаа не працює)
if (!this.config?.path) {
            console.warn('table-array-collection-controller: add "path" property to config');
            return;
        }
        
а так сейв метот наповнений логікою яка йому не потрібна

2024-04-24 13:56 UTC, Kaskyi commented on packages/components/table/collections/xm-table-array-collection-controller.ts
> +        if (this.config?.save?.controller) {
заставляємете мене рефакторити

```ts
type DynamicKey = string;
type ObservableMethodKey = string;

export interface XmTableArrayCollectionControllerConfig extends XmTableEntity {
    type: 'array',
    entityController: {
        key: DynamicKey,
        method: ObservableKey;
    },
    save: {
        controller: {
            key: DynamicKey;
            method: ObservableMethodKey;
        }
    }
}

@Injectable()
export class XmTableArrayCollectionController<T = unknown>
    extends AXmTableLocalPageableCollectionController<T>
    implements IXmTableCollectionController<T> {
    private _config: XmTableArrayCollectionControllerConfig;
    private entity: object;

    public set config(value: XmTableArrayCollectionControllerConfig) {
        if (!value || !value.path) {
            throw Error('table-array-collection-controller: add "path" property to config');
        }
        this._config = value;
        this._config.entityController.key = this._config.entityController.key || 'table-entity-controller';
        this._config.entityController.method = this._config.entityController.method || 'update';
        
    }

    public add(item: T): void {
        const {uuidKeyName} = this.config;
        if (uuidKeyName) {
            item[uuidKeyName] = UUID.UUID();
        }

        super.add(item);
    }

    public save(): void {
        set(this.entity, this.config.path, cloneDeep(this.items));
        const saveResult = this.getEntityController()[this.config.save.controller.method](this.entity);
        saveResult
            .pipe(first())
            .subscribe();
    }

    private getEntityController(): XmTableEntityController<object> | any {
        return this.xmDynamicInstanceService.getControllerByKey(
            this.config.save.controller.key,
            this.injector,
        ) || this.entityController;
    }

}
```

2024-04-24 14:10 UTC, Kaskyi commented on packages/components/table/collections/xm-table-array-collection-controller.ts
> +        if (this.config?.save?.controller) {
ну можна зробити проксю для динамічних методів
```ts
this.dynamicAdapter.execute<ResponseType>('key','method', [arguments]).subscribe(result)
```