fix: add custom date adapter
xm-online/xm-webapp pull request #2124
Opened 2024-06-19 11:27 UTC by Olensavchenko

2024-06-19 11:35 UTC, Bozonych approved these changes

2024-06-19 12:17 UTC, zverbeta requested changes

2024-06-19 12:17 UTC, zverbeta commented on packages/components/date/shared/custom-date-adapter.ts
> +        if (typeof value === 'string' && value.indexOf('.') > -1) {
Should we use dayjs library for stuff like this

2024-06-21 14:07 UTC, LevBD approved these changes

2024-06-21 14:18 UTC, Olensavchenko commented on packages/components/date/shared/custom-date-adapter.ts
> +        if (typeof value === 'string' && value.indexOf('.') > -1) {
will be changed in next pr

2024-06-21 14:27 UTC, zverbeta reviewed
We will fix it in next pr

2024-06-21 15:13 UTC, zverbeta approved these changes

2024-06-21 15:14 UTC, merged