feat(slide-toggle): add slide-toggle control component
xm-online/xm-webapp pull request #2255
Opened 2024-12-11 13:11 UTC by Sumragen

2024-12-11 13:46 UTC, LevBD approved these changes

2024-12-11 15:00 UTC, zverbeta requested changes
Could we avoid using NgFormAccessor?

2024-12-12 07:18 UTC, Sumragen commented on packages/components/bool/slide-toggle/slide-toggle-control.component.ts
> +import { NgFormAccessor } from '@xm-ngx/components/ng-accessor';
done

2024-12-12 07:33 UTC, zverbeta approved these changes

2024-12-12 07:40 UTC, merged