fix(b2bcrm-800) add filter by unique id and hide TypeError
xm-online/xm-webapp pull request #747
Opened 2020-09-29 13:00 UTC by EKrasovskiy

2020-09-29 13:39 UTC, Kaskyi approved these changes

2020-09-30 07:46 UTC, Sumragen requested changes

2020-09-30 07:46 UTC, Sumragen commented on packages/administration/src/admin.service.ts
>      public onSuccess(data: any, headers: any): any {
We could specify interface of `data` parameter. At least we knew property `id`

2020-09-30 07:47 UTC, EKrasovskiy commented on packages/administration/src/admin.service.ts
>      public onSuccess(data: any, headers: any): any {
yes, ok.

2020-09-30 07:48 UTC, Sumragen commented
Also specify all typings that we know, please.
![image](https://user-images.githubusercontent.com/15640910/94657703-83c1bb00-030a-11eb-9bc2-d921eda2cbce.png)

2020-09-30 09:06 UTC, Sumragen approved these changes

2020-09-30 10:09 UTC, merged