chore(date): update date naming
xm-online/xm-webapp pull request #838
Opened 2020-11-20 12:04 UTC by Kaskyi

2020-11-20 12:29 UTC, Sumragen requested changes

2020-11-20 12:29 UTC, Sumragen commented on packages/components/date/examples/xm-date-example.ts
> +    public dateControlOptions: XmDateControlOptions = { title: 'date-control-view', name: 'date-control-view' };
It looks like word date is redundant in property name due to we have described domain in component name.

2020-11-20 12:29 UTC, Sumragen commented on packages/components/date/testing/xm-date-testing.module.ts
> +export class XmDateTestingModule {
Sounds like we will import some part of logic that will manipulate/calculate date objects

2020-11-20 12:29 UTC, Sumragen commented on packages/components/date/xm-date-view.ts
> +    public styleInline: boolean;
could we remove that property? It looks like we could retrieve necessary value from config directrly.

2020-11-20 12:29 UTC, Sumragen commented on packages/components/date/date.md
> +`xm-date-view` = date view
should symbol `=` to be `-`?

2020-11-20 12:35 UTC, Kaskyi commented on packages/components/date/date.md
> +`xm-date-view` = date view
+

2020-11-20 12:39 UTC, Kaskyi commented on packages/components/date/xm-date-view.ts
> +    public styleInline: boolean;
no - where will be a typing error

2020-11-20 12:51 UTC, Kaskyi commented on packages/components/date/examples/xm-date-example.ts
> +    public dateControlOptions: XmDateControlOptions = { title: 'date-control-view', name: 'date-control-view' };
`value` and `options` won't be self-described and it is easier to tell which component it belongs to

2020-11-20 12:57 UTC, Kaskyi commented on packages/components/date/testing/xm-date-testing.module.ts
> +export class XmDateTestingModule {
\+

2020-11-20 13:44 UTC, Sumragen requested changes

2020-11-20 13:44 UTC, Sumragen commented on packages/components/date/examples/xm-date-example.ts
> +    public dateControlOptions: XmDateControlOptions = { title: 'date-control-view', name: 'date-control-view' };
why is it? In case when I use component `xm-date-example` it quite clearly for me that value of it will be `Date`, isn't? As an example when we use component `username-label` it's quite clear that value is some username.

2020-11-20 13:44 UTC, Sumragen commented on packages/components/date/xm-date-view.ts
> +    public styleInline: boolean;
which one? We could use `!!` syntax to transform value.

2020-11-21 07:05 UTC, EKrasovskiy approved these changes

2020-11-23 10:30 UTC, Sumragen approved these changes

2020-11-23 10:31 UTC, merged