feat(content-uploader): base64 file loader for master
xm-online/xm-webapp pull request #979
Opened 2021-03-29 07:40 UTC by dprimak

2021-03-29 08:31 UTC, sergeysenja1992 commented on src/app/shared/jsf-extention/jsf-attributes-helper.ts
> +        'content-uploader': ContentUploaderComponent,
what different between FileUploadComponent and ContentUploaderComponent?

2021-03-29 08:31 UTC, andrewkikot commented on src/app/shared/jsf-extention/widgets/content-uploader/content-uploader.component.scss
> +::ng-deep {
it is bad practice to use ng-deep like this
pls, consider using it with ::host or custom class wrapper

2021-03-29 08:31 UTC, andrewkikot commented on src/app/shared/jsf-extention/widgets/content-uploader/content-uploader.component.scss
> +.upload-file {
can we use ::host or class wrapper to avoid this importants?

2021-03-29 08:31 UTC, andrewkikot commented on src/app/shared/jsf-extention/widgets/content-uploader/content-uploader.component.ts
> +        console.warn(err);
remove pls

2021-03-29 08:37 UTC, sergeysenja1992 commented on src/app/shared/jsf-extention/widgets/content-uploader/content-uploader.component.ts
> +            this.uploadProcess = this.httpClient
idea of this component it's send content as base64 json filed when we submit form with all other data.

separate post broke this idea

2021-03-29 09:05 UTC, dprimak commented on src/app/shared/jsf-extention/widgets/content-uploader/content-uploader.component.ts
> +            this.uploadProcess = this.httpClient
не совсем понял, таким же образом работает обычный file-uploader

2021-03-29 09:08 UTC, dprimak commented on src/app/shared/jsf-extention/jsf-attributes-helper.ts
> +        'content-uploader': ContentUploaderComponent,
ContentUploaderComponent загружает файл в формате base64

2021-03-29 09:39 UTC, dprimak commented on src/app/shared/jsf-extention/widgets/content-uploader/content-uploader.component.scss
> +.upload-file {
+

2021-03-29 09:39 UTC, dprimak commented on src/app/shared/jsf-extention/widgets/content-uploader/content-uploader.component.ts
> +        console.warn(err);
+

2021-03-29 11:05 UTC, sergeysenja1992 commented on src/app/shared/jsf-extention/widgets/content-uploader/content-uploader.component.ts
> +            this.uploadProcess = this.httpClient
pls use English on public repository

2021-03-29 11:06 UTC, sergeysenja1992 requested changes
file-upload duplicate

need to be changed to send on form submit

2021-03-30 11:26 UTC, andrewkikot approved these changes

2021-04-05 11:31 UTC, sergeysenja1992 approved these changes

2021-04-05 12:00 UTC, merged